name: Explosivechestprotect
version: ${project.version}
main: iman.engineer.explosivechestprotect.Explosivechestprotect
api-version: 1.13
authors: [Hoofer]
description: Protect chests from explosions
website: iman.engineer
